name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: npm i -g newman
    - run: newman run newsapi.json --env-var "envApiKey=144e0c5c31324ea199b7e9cb410e96d0"
